"""Ajout des patients

Revision ID: 47d7ae4a8422
Revises: 49214fba7801
Create Date: 2024-06-24 06:30:15.640643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47d7ae4a8422'
down_revision = '49214fba7801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fever', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('fatigue', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('muscle_aches', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('headache', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('vomiting', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('diarrhea', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.alter_column('meat_consumption',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.drop_column('symptoms')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptoms', mysql.TEXT(), nullable=False))
        batch_op.alter_column('meat_consumption',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('additional_info')
        batch_op.drop_column('diarrhea')
        batch_op.drop_column('vomiting')
        batch_op.drop_column('headache')
        batch_op.drop_column('muscle_aches')
        batch_op.drop_column('fatigue')
        batch_op.drop_column('fever')

    # ### end Alembic commands ###
