"""Ajout des patients

Revision ID: 49a4b9daa42d
Revises: 5e826434adde
Create Date: 2024-06-22 16:41:48.462030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a4b9daa42d'
down_revision = '5e826434adde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suivi_par', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'utilisateur', ['suivi_par'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('suivi_par')

    # ### end Alembic commands ###
