"""Ajout des patients

Revision ID: 5e826434adde
Revises: 
Create Date: 2024-06-21 19:38:25.596451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e826434adde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['session_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_token')

    # ### end Alembic commands ###
