"""Ajout des patients

Revision ID: b87e1c4e4c71
Revises: 47d7ae4a8422
Create Date: 2024-06-26 15:29:48.949352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87e1c4e4c71'
down_revision = '47d7ae4a8422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_telephone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_creation_compte', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('date_creation_compte')
        batch_op.drop_column('numero_telephone')

    # ### end Alembic commands ###
